"""
Django settings for emprendeespiritu project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

from celery.schedules import crontab

from emprendeespiritu.app.utils.tz import get_utc_crontab_kwargs

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'efv!11l4^x=5=$lrfeki_evrgl=5b^ny^=+4dg&@0o^xp^55^l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compressor',
    'djcelery',
    'djrill',
    'kombu.transport.django',
    'emprendeespiritu.app.blog',
    'emprendeespiritu.app.comentarios',
    'emprendeespiritu.app.cursos',
    'emprendeespiritu.app.galeria',
    'emprendeespiritu.app.perfil',
    'emprendeespiritu.app.productos',
    'emprendeespiritu.app.talleres',
    'emprendeespiritu.app.home',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

STATICFILES_FINDERS = (
    'compressor.finders.CompressorFinder',
)

ROOT_URLCONF = 'emprendeespiritu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.realpath(os.path.join(BASE_DIR, 'emprendeespiritu/templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'emprendeespiritu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'emprendeespiritu.sqlite3'),
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES' : (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication'
    )
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es-MX'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Celery scheduled tasks
CELERY_TIMEZONE = 'CST'

CELERY_ALWAYS_EAGER = True

CELERY_ACKS_LATE = True

CELERYBEAT_SCHEDULE = {
    'send-daily-mails-courses': {
        'task': 'emprendeespiritu.app.email.tasks.send_daily_mails',
        'schedule': crontab(**get_utc_crontab_kwargs(hour=17, minute=53))
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/assets/'

MANDRILL_API_KEY = 'dElSPvXjpLzqnJpo8rpzgg'

#EMAIL_BACKEND = 'djrill.mail.backends.djrill.DjrillBackend'
EMAIL_HOST = "localhost"
DEFAULT_FROM_EMAIL = "pruebas.emprende.espiritu@gmail.com"
EMAIL_PORT = 25
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'pruebas.emprende.espiritu@gmail.com'
EMAIL_HOST_PASSWORD = 'Emprende2015'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Batch emailing
MAX_EMAILS_SENT_PER_HOUR = 75

EMAILS_SENDING_INTERVAL = 15

BATCH_ACTUALIZATION_INTERVAL = 10


STATICFILES_DIRS = (
    os.path.realpath(os.path.join(BASE_DIR, 'media','assets')),
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)

MEDIA_ROOT = os.path.realpath(
    os.path.join(BASE_DIR, 'media', 'assets','uploads')
)

COMPRESS_ROOT = os.path.realpath(os.path.join(BASE_DIR, 'media','assets'))

COMPRESS_ENABLED = False

#CELERY
BROKER_URL = 'django://'
CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend'
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]